# Generated by Django 3.2.5 on 2024-04-05 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConfiguracionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Nombre del usuario')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=70)),
                ('cargo', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('token', models.UUIDField(blank=True, editable=False, null=True)),
                ('estado', models.BooleanField(default=0)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.agencia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FechaHora', models.DateTimeField()),
                ('Actividad', models.CharField(max_length=80)),
                ('Nivel', models.CharField(max_length=15)),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
                'db_table': 'Bitacora',
            },
        ),
    ]
