# Generated by Django 3.2.5 on 2024-04-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreDepa', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreMuni', models.CharField(max_length=70)),
                ('Estado', models.IntegerField()),
                ('IdDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DireccionApp.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Distrito', models.CharField(max_length=100)),
                ('Estado', models.IntegerField()),
                ('IdMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DireccionApp.municipio')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'db_table': 'Distrito',
            },
        ),
    ]
