# Generated by Django 3.2.5 on 2024-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DireccionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='NombreDepa',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='Distrito',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='NombreMuni',
            field=models.CharField(max_length=22),
        ),
    ]
