# Generated by Django 3.2.5 on 2024-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluacionMicroApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesitumic',
            name='TipoNego',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='capacidadpagomic',
            name='PorcentajeCuot',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='capacidadpagomic',
            name='PorcentajeDisp',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='capacidadpagomic',
            name='PorcentajeEnde',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='Afp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='Alimentacion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='Alquiler',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='Educacion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='Imprevistos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='OtrosDesc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='PorcentajeHplhes',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='PorcentajePlan',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='PorcentajeVent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='Recreacion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='Salud',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='Servicios',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='egresoflujmic',
            name='Transporte',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingresoflujmic',
            name='Remesas',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
