# Generated by Django 3.2.5 on 2024-04-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SolicitudesApp', '0001_initial'),
        ('ConfiguracionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosclie',
            name='IdSolicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.solicitud'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='IdTasaInte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.tasainte'),
        ),
    ]
