# Generated by Django 3.2.5 on 2024-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfiguracionApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='Departamento',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='Direccion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='Distrito',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='Municipio',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='Alternativa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documentosclie',
            name='NombreDocu',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='Nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='Tipo',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='TipoLoteMej',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelovivi',
            name='Descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='modelovivi',
            name='Modelo',
            field=models.FileField(blank=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='modelovivi',
            name='MontoCons',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='modelovivi',
            name='TipoVivi',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rangofina',
            name='VecesFina',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salario',
            name='TipoSala',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='solicitudinscsegenf',
            name='Personal',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tasainte',
            name='NumeroCred',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipooper',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='zonaagen',
            name='NombreZona',
            field=models.CharField(max_length=25),
        ),
    ]
