# Generated by Django 3.2.5 on 2024-04-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConfiguracionApp', '0002_initial'),
        ('SolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionMejo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.CharField(max_length=20)),
                ('TelefonoPrim', models.CharField(max_length=10)),
                ('TelefonoSegu', models.CharField(max_length=10)),
                ('TerceraEdad', models.CharField(max_length=10)),
                ('Adultos', models.CharField(max_length=10)),
                ('Ninos', models.CharField(max_length=10)),
                ('PersonaDisc', models.CharField(max_length=10)),
                ('PropietarioInmu', models.CharField(max_length=100)),
                ('ParentescoSoli', models.CharField(max_length=50)),
                ('Latitud', models.CharField(max_length=100)),
                ('Longitud', models.CharField(max_length=100)),
                ('Inmueble', models.CharField(max_length=10)),
                ('UsoActu', models.CharField(max_length=15)),
                ('ExisteOtrViv', models.CharField(max_length=5)),
                ('UsoActuOtrViv', models.CharField(max_length=15)),
                ('ComentariosRelv', models.CharField(max_length=200)),
                ('IdSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.solicitud')),
            ],
            options={
                'verbose_name': 'InspeccionMejo',
                'verbose_name_plural': 'InspeccionMejos',
                'db_table': 'InspeccionMejo',
            },
        ),
        migrations.CreateModel(
            name='ViasAcceInsMej',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TipoVias', models.CharField(max_length=35)),
                ('IdInspeccionMejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionmejo')),
            ],
            options={
                'verbose_name': 'ViasAcceInsMej',
                'verbose_name_plural': 'ViasAcceInsMejs',
                'db_table': 'ViasAcceInsMej',
            },
        ),
        migrations.CreateModel(
            name='RiesgosInsMej',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DistanciaTalu', models.CharField(max_length=15)),
                ('DistanciaRiosCer', models.CharField(max_length=15)),
                ('DistanciaLadeCer', models.CharField(max_length=15)),
                ('DistanciaTorrCer', models.CharField(max_length=15)),
                ('IdInspeccionMejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionmejo')),
            ],
            options={
                'verbose_name': 'RiesgosInsMej',
                'verbose_name_plural': 'RiesgosInsMejs',
                'db_table': 'RiesgosInsMej',
            },
        ),
        migrations.CreateModel(
            name='PrimeraInspMej',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroInsp', models.CharField(max_length=25)),
                ('Fecha', models.DateField()),
                ('MejoraReal', models.CharField(max_length=300)),
                ('Esquema', models.FileField(blank=True, upload_to='documentos/')),
                ('IdInspeccionMejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionmejo')),
            ],
            options={
                'verbose_name': 'PrimeraInspMej',
                'verbose_name_plural': 'PrimeraInspMejs',
                'db_table': 'PrimeraInspMej',
            },
        ),
        migrations.CreateModel(
            name='PlanMejoInsMej',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Etapas', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=300)),
                ('IdInspeccionMejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionmejo')),
            ],
            options={
                'verbose_name': 'PlanMejoInsMej',
                'verbose_name_plural': 'PlanMejoInsMejs',
                'db_table': 'PlanMejoInsMej',
            },
        ),
        migrations.CreateModel(
            name='InspeccionMejoEspSerInfRie',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Existe', models.CharField(max_length=10)),
                ('IdInfraestructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.infraestructura')),
                ('IdInspeccionMejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionmejo')),
            ],
            options={
                'verbose_name': 'InspeccionMejoEspSerInfRie',
                'verbose_name_plural': 'InspeccionMejoEspSerInfRies',
                'db_table': 'InspeccionMejoEspSerInfRie',
            },
        ),
        migrations.CreateModel(
            name='InfraestructuraInmuInsMej',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Existe', models.CharField(max_length=10)),
                ('Estado', models.CharField(max_length=10)),
                ('TipoSist', models.CharField(max_length=100)),
                ('IdInfraestructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.infraestructura')),
                ('IdInspeccionMejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionmejo')),
            ],
            options={
                'verbose_name': 'InfraestructuraInmuInsMej',
                'verbose_name_plural': 'InfraestructuraInmuInsMejs',
                'db_table': 'InfraestructuraInmuInsMej',
            },
        ),
        migrations.CreateModel(
            name='ImagenPrimInsMej',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.FileField(blank=True, upload_to='documentos/')),
                ('IdPrimeraInspMej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.primerainspmej')),
            ],
            options={
                'verbose_name': 'ImagenPrimInsMej',
                'verbose_name_plural': 'ImagenPrimInsMejs',
                'db_table': 'ImagenPrimInsMej',
            },
        ),
        migrations.CreateModel(
            name='FactibilidadInsMej',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Detalle', models.CharField(max_length=300)),
                ('IdInspeccionMejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionmejo')),
            ],
            options={
                'verbose_name': 'FactibilidadInsMej',
                'verbose_name_plural': 'FactibilidadInsMejs',
                'db_table': 'FactibilidadInsMej',
            },
        ),
        migrations.CreateModel(
            name='EsquemasInspMej',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('EsquemaSiti', models.FileField(blank=True, upload_to='documentos/')),
                ('EsquemaMejo', models.FileField(blank=True, upload_to='documentos/')),
                ('IdInspeccionMejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionmejo')),
            ],
            options={
                'verbose_name': 'EsquemasInspMej',
                'verbose_name_plural': 'EsquemasInspMejs',
                'db_table': 'EsquemasInspMej',
            },
        ),
        migrations.CreateModel(
            name='DescripcionMejoInsMej',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=300)),
                ('DiasEsti', models.CharField(max_length=10)),
                ('IdInspeccionMejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionMejViviendaApp.inspeccionmejo')),
            ],
            options={
                'verbose_name': 'DescripcionMejoInsMej',
                'verbose_name_plural': 'DescripcionMejoInsMejs',
                'db_table': 'DescripcionMejoInsMej',
            },
        ),
    ]
