# Generated by Django 3.2.5 on 2024-04-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCheq',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('SolicitudCred', models.CharField(max_length=5, null=True)),
                ('FotocopiaDui', models.CharField(max_length=5, null=True)),
                ('RecibosAgua', models.CharField(max_length=5, null=True)),
                ('RecibosLuz', models.CharField(max_length=5, null=True)),
                ('RecibosTele', models.CharField(max_length=5, null=True)),
                ('ReferenciaCred', models.CharField(max_length=5, null=True)),
                ('ConstanciaEmpl', models.CharField(max_length=5, null=True)),
                ('TacoIsss', models.CharField(max_length=5, null=True)),
                ('AnalisisEcon', models.CharField(max_length=5, null=True)),
                ('Balance', models.CharField(max_length=5, null=True)),
                ('BalanceResu', models.CharField(max_length=5, null=True)),
                ('CopiaDuiFia', models.CharField(max_length=5, null=True)),
                ('RecibosAguaFia', models.CharField(max_length=5, null=True)),
                ('RecibosLuzFia', models.CharField(max_length=5, null=True)),
                ('ConstanciaEmplFia', models.CharField(max_length=5, null=True)),
                ('ReferenciaCredFia', models.CharField(max_length=5, null=True)),
                ('InspeccionTecn', models.CharField(max_length=5, null=True)),
                ('PresupuestoCons', models.CharField(max_length=5, null=True)),
                ('CertificadoExtr', models.CharField(max_length=5, null=True)),
                ('CarenciaBien', models.CharField(max_length=5, null=True)),
                ('FotocopiaEscr', models.CharField(max_length=5, null=True)),
                ('DeclaracionSalu', models.CharField(max_length=5, null=True)),
                ('InformeDico', models.CharField(max_length=5, null=True)),
                ('DocumentoSopoIng', models.CharField(max_length=5, null=True)),
                ('DocumentoReme', models.CharField(max_length=5, null=True)),
                ('CancelacionesPresEst', models.CharField(max_length=5, null=True)),
                ('Finiquitos', models.CharField(max_length=5, null=True)),
                ('HojaAproCre', models.CharField(max_length=5, null=True)),
                ('CartaElabMut', models.CharField(max_length=5, null=True)),
                ('ReciboPagoPri', models.CharField(max_length=5, null=True)),
                ('OrdenDeseIrr', models.CharField(max_length=5, null=True)),
                ('PermisoCons', models.CharField(max_length=5, null=True)),
                ('CartaEntrCosdes', models.CharField(max_length=5, null=True)),
                ('FotocopiaMutu', models.CharField(max_length=5, null=True)),
                ('GestionCobr', models.CharField(max_length=5, null=True)),
                ('Estado', models.CharField(max_length=10)),
                ('IdSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.solicitud')),
            ],
            options={
                'verbose_name': 'ListaCheq',
                'verbose_name_plural': 'ListaCheqs',
                'db_table': 'ListaCheq',
            },
        ),
    ]
