# Generated by Django 3.2.5 on 2024-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListaChequeoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listacheq',
            name='AnalisisEcon',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='Balance',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='BalanceResu',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='CancelacionesPresEst',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='CarenciaBien',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='CartaElabMut',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='CartaEntrCosdes',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='CertificadoExtr',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='ConstanciaEmpl',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='ConstanciaEmplFia',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='CopiaDuiFia',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='DeclaracionSalu',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='DocumentoReme',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='DocumentoSopoIng',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='Finiquitos',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='FotocopiaDui',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='FotocopiaEscr',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='FotocopiaMutu',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='GestionCobr',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='HojaAproCre',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='InformeDico',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='InspeccionTecn',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='OrdenDeseIrr',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='PermisoCons',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='PresupuestoCons',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='ReciboPagoPri',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='RecibosAgua',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='RecibosAguaFia',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='RecibosLuz',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='RecibosLuzFia',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='RecibosTele',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='ReferenciaCred',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='ReferenciaCredFia',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='SolicitudCred',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listacheq',
            name='TacoIsss',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
