# Generated by Django 3.2.5 on 2024-04-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClienteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresosFami',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Alimentacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Educacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Transporte', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Salud', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Afp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Servicios', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Alquiler', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PorcentajePlan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PorcentajeVent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PorcentajeHplhes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('OtrosDesc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Recreacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Imprevistos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Estado', models.IntegerField()),
                ('IdPerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClienteApp.perfil')),
            ],
            options={
                'verbose_name': 'EgresosFami',
                'verbose_name_plural': 'EgresosFamis',
                'db_table': 'EgresosFami',
            },
        ),
        migrations.CreateModel(
            name='IngresosFami',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Familiar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('OtrosIngr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TotalIngr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IdEgresosFami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvaluacionIvEFApp.egresosfami')),
            ],
            options={
                'verbose_name': 'IngresosFami',
                'verbose_name_plural': 'IngresosFamis',
                'db_table': 'IngresosFami',
            },
        ),
        migrations.CreateModel(
            name='CapacidadPagoFam',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PorcentajeEnde', models.CharField(max_length=10)),
                ('Disponible', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PorcentajeDisp', models.CharField(max_length=10)),
                ('Cuota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PorcentajeCuot', models.CharField(max_length=10)),
                ('Superavit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Deficit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Estado', models.CharField(max_length=10)),
                ('IdEgresosFami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvaluacionIvEFApp.egresosfami')),
            ],
            options={
                'verbose_name': 'CapacidadPagoFam',
                'verbose_name_plural': 'CapacidadPagoFams',
                'db_table': 'CapacidadPagoFam',
            },
        ),
        migrations.CreateModel(
            name='BienesHoga',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.CharField(max_length=10, null=True)),
                ('DescripcionBien', models.CharField(max_length=100, null=True)),
                ('PrecioComp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('CuotaMens', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('IdEgresosFami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvaluacionIvEFApp.egresosfami')),
            ],
            options={
                'verbose_name': 'BienesHoga',
                'verbose_name_plural': 'BienesHogas',
                'db_table': 'BienesHoga',
            },
        ),
    ]
