# Generated by Django 3.2.5 on 2024-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeclaracionJurClienteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionactieco',
            name='EspecificarOtraAct',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='declaracionjuracli',
            name='CanceladoAcueCuo',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='declaracionjuracli',
            name='Cuota',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaracionjuracli',
            name='FormaPago',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='declaracionjuracli',
            name='Monto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaracionjuracli',
            name='NombrePersNat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='declaracionjuracli',
            name='Plazo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='declaracionjuracli',
            name='ProcedenciaFond',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='declaracionjuracli',
            name='RealizarPagoAdi',
            field=models.CharField(max_length=3),
        ),
    ]
