# Generated by Django 3.2.5 on 2024-04-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConfiguracionApp', '0002_initial'),
        ('SolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionLote',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.CharField(max_length=15)),
                ('TelefonoPrim', models.CharField(max_length=10)),
                ('TelefonoSegu', models.CharField(max_length=10)),
                ('TerceraEdad', models.CharField(max_length=10)),
                ('Adultos', models.CharField(max_length=10)),
                ('Ninos', models.CharField(max_length=10)),
                ('PersonaDisc', models.CharField(max_length=10)),
                ('PropietarioTerr', models.CharField(max_length=100)),
                ('Latitud', models.CharField(max_length=100)),
                ('Longitud', models.CharField(max_length=100)),
                ('Inmueble', models.CharField(max_length=10)),
                ('ExisteOtraViv', models.CharField(max_length=5)),
                ('TerrenoAgri', models.CharField(max_length=5)),
                ('AnchoConsViv', models.CharField(max_length=15)),
                ('LargoConsViv', models.CharField(max_length=15)),
                ('AreaConsViv', models.CharField(max_length=15)),
                ('AnchoAmplFut', models.CharField(max_length=15)),
                ('LargoAmplFut', models.CharField(max_length=15)),
                ('AreaAmplFut', models.CharField(max_length=15)),
                ('IdSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.solicitud')),
            ],
            options={
                'verbose_name': 'InspeccionLote',
                'verbose_name_plural': 'InspeccionLotes',
                'db_table': 'InspeccionLote',
            },
        ),
        migrations.CreateModel(
            name='ViasAcceInsLot',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TipoVias', models.CharField(max_length=35)),
                ('IdInspeccionLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionLoteApp.inspeccionlote')),
            ],
            options={
                'verbose_name': 'ViasAcceInsLot',
                'verbose_name_plural': 'ViasAcceInsLots',
                'db_table': 'ViasAcceInsLot',
            },
        ),
        migrations.CreateModel(
            name='RiesgosInspLot',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DistanciaTalu', models.CharField(max_length=15)),
                ('DistanciaRiosCer', models.CharField(max_length=15)),
                ('DistanciaLadeCer', models.CharField(max_length=15)),
                ('DistanciaTorrAnt', models.CharField(max_length=15)),
                ('IdInspeccionLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionLoteApp.inspeccionlote')),
            ],
            options={
                'verbose_name': 'RiesgosInspLot',
                'verbose_name_plural': 'RiesgosInspLots',
                'db_table': 'RiesgosInspLot',
            },
        ),
        migrations.CreateModel(
            name='ResponsabilidadSoliInsLot',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('MojonesLote', models.CharField(max_length=5)),
                ('LinderosLote', models.CharField(max_length=5)),
                ('ResguardoMate', models.CharField(max_length=5)),
                ('AuxiliaresCons', models.CharField(max_length=5)),
                ('AguaPota', models.CharField(max_length=5)),
                ('EnergiaElec', models.CharField(max_length=5)),
                ('IdInspeccionLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionLoteApp.inspeccionlote')),
            ],
            options={
                'verbose_name': 'ResponsabilidadSoliInsLot',
                'verbose_name_plural': 'ResponsabilidadSoliInsLots',
                'db_table': 'ResponsabilidadSoliInsLot',
            },
        ),
        migrations.CreateModel(
            name='PrimeraInspLot',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroInsp', models.CharField(max_length=25)),
                ('Fecha', models.DateField()),
                ('Esquema', models.FileField(blank=True, upload_to='documentos/')),
                ('Ubicacion', models.FileField(blank=True, upload_to='documentos/')),
                ('IdInspeccionLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionLoteApp.inspeccionlote')),
            ],
            options={
                'verbose_name': 'PrimeraInspLot',
                'verbose_name_plural': 'PrimeraInspLots',
                'db_table': 'PrimeraInspLot',
            },
        ),
        migrations.CreateModel(
            name='InspeccionLoteConInfSanSerRie',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Existe', models.CharField(max_length=5)),
                ('IdInfraestructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.infraestructura')),
                ('IdInspeccionLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionLoteApp.inspeccionlote')),
            ],
            options={
                'verbose_name': 'InspeccionLoteConInfSanSerRie',
                'verbose_name_plural': 'InspeccionLoteConInfSanSerRies',
                'db_table': 'InspeccionLoteConInfSanSerRie',
            },
        ),
        migrations.CreateModel(
            name='ImagenPrimInsLot',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ReporteFoto', models.FileField(blank=True, upload_to='documentos/')),
                ('IdPrimeraInspLot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionLoteApp.primerainsplot')),
            ],
            options={
                'verbose_name': 'ImagenPrimInsLot',
                'verbose_name_plural': 'ImagenPrimInsLots',
                'db_table': 'ImagenPrimInsLot',
            },
        ),
        migrations.CreateModel(
            name='FactibilidadInsLot',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Detalle', models.CharField(max_length=300)),
                ('IdInspeccionLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionLoteApp.inspeccionlote')),
            ],
            options={
                'verbose_name': 'FactibilidadInsLot',
                'verbose_name_plural': 'FactibilidadInsLots',
                'db_table': 'FactibilidadInsLot',
            },
        ),
        migrations.CreateModel(
            name='DescripcionProyInsLot',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ModeloViviCon', models.CharField(max_length=30)),
                ('SolucionSaniPro', models.CharField(max_length=300)),
                ('ObrasAdicCon', models.CharField(max_length=300)),
                ('ObservacionesTecn', models.CharField(max_length=400)),
                ('ActividadRespFia', models.CharField(max_length=500)),
                ('IdInspeccionLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionLoteApp.inspeccionlote')),
            ],
            options={
                'verbose_name': 'DescripcionProyInsLot',
                'verbose_name_plural': 'DescripcionProyInsLots',
                'db_table': 'DescripcionProyInsLot',
            },
        ),
        migrations.CreateModel(
            name='ComentariosObseInsLot',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Comentarios', models.CharField(max_length=400)),
                ('Observaciones', models.CharField(max_length=400)),
                ('IdInspeccionLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InspeccionLoteApp.inspeccionlote')),
            ],
            options={
                'verbose_name': 'ComentariosObseInsLot',
                'verbose_name_plural': 'ComentariosObseInsLots',
                'db_table': 'ComentariosObseInsLot',
            },
        ),
    ]
