from fpdf import FPDF
from datetime import date
import locale
from ClienteApp.models import *

from django.http import FileResponse
from SolicitudesApp.models import *
from ConozcaClienteApp.models import *
from ConfiguracionApp.models import Ocupacion


class ConozcaC(FPDF):
    
    def conozcaClie(request, id ):
        locale.setlocale(locale.LC_TIME, '')
        fecha=date.today()
        
        try:    
            cdg=ClienteDatoGen.objects.get(Id=id)
        except ClienteDatoGen.DoesNotExist:
            cdg=""
         
        #########################################
        idSol=cdg.IdSolicitud.Id
        try:
            s=  Solicitud.objects.filter(Id=idSol)
        except Solicitud.DoesNotExist:
            s=""

        idp=cdg.IdSolicitud.IdPerfil.Id
        try:
            perf=  Perfil.objects.get(Id=idp)
        except Perfil.DoesNotExist:
            perf=""        
       
        
        try:
            d=  Domicilio.objects.get(IdSolicitud=idSol, Tipo="Solicitante")
        except Domicilio.DoesNotExist:
            d=""

        try:
            dp=DatosPers.objects.get(IdSolicitud=idSol)
        except DatosPers.DoesNotExist:
            dp=""

        try:
            dpc=DatosPersFia.objects.get(IdSolicitud=idSol,Tipo = "codeudor")
        except Exception:
            dpc=""
    ##########################################

        try:
            cdaec=  ClienteActiEco.objects.get(IdClienteDatoGen=id)
        except ClienteActiEco.DoesNotExist:
            cdaec=""
        try: 
            cddn= ClienteDatoNeg.objects.get(IdClienteDatoGen=id)
        except ClienteDatoNeg.DoesNotExist:
            cddn="" 
        try: 
            cdrrf= ClienteReciRemFam.objects.filter(IdClienteDatoGen=id)
        except ClienteReciRemFam.DoesNotExist:
            cdrrf=""

        try: 
            cdrrfc= ClienteReciRemFam.objects.get(IdClienteDatoGen=id)
        except ClienteReciRemFam.DoesNotExist:
            cdrrfc=""

        try:
            cdc=  ClienteDeclCli.objects.get(IdClienteDatoGen=id)
        except ClienteDeclCli.DoesNotExist:
            cdc=""
        
        try:
            cdpbo=  ClientePersBen.objects.get(IdClienteDatoGen=id)
        except ClientePersBen.DoesNotExist:
            cdpbo=""

        try:
            cpt=  ClientePerfTra.objects.get(IdClienteDatoGen=id)
        except ClientePerfTra.DoesNotExist:
            cpt=""
        try:
            cpeps=  ClientePeps.objects.get(IdClienteDatoGen=id)
        except ClientePeps.DoesNotExist:
            cpeps=""
        try:
            cpus=  ClienteParaUsoExc.objects.get(IdClienteDatoGen=id)
        except ClienteParaUsoExc.DoesNotExist:
            cpus=""
        

        r=59
        g=93
        b=149
        aux=[0, 1, 2, 3]
        aux2=[0, 1, 2]    
        pdf=FPDF(orientation='P', unit='mm', format='Letter')
        pdf.add_page()
        #pdf.multi_cell(w=0, h=40, txt='', border=1)
        
        pdf.set_font('Arial', 'B', 12)
        pdf.set_fill_color(r,g,b)
        pdf.set_text_color(255,255,255)
        pdf.cell(w=0,h=8,txt='ASOCIACIÓN HPH EL SALVADOR', border='TRL',  align='C', fill=True, ln=1)
        pdf.cell(w=0,h=7,txt='CONOZCA A SU CLIENTE', border='LR',  align='C', fill=True, ln=1)
        pdf.set_font('Arial', 'B', 9)
        pdf.cell(w=0,h=5,txt='Estrictamente confidencial', border='BLR',  align='R', fill=True, ln=1)
        pdf.image('TesisApp/static/TesisApp/images/logohabitatb.png', x=7, y=5, w=40, h=30)#, link=url) 
        pdf.set_font('Arial', '', 10)
        pdf.set_y(30)
        pdf.set_left_margin(10)
        pdf.set_text_color(r,g,b)
        #pdf.add_page
        pdf.set_text_color(255,255,255)
        #pdf.cell(w=0,h=5,txt='', border='B',  align='L', ln=1, fill=0)        
        pdf.cell(w=0,h=10,txt='PERSONA NATURAL', border=1,  align='C', fill=True, ln=1)
        pdf.cell(w=196,h=6,txt='DATOS GENERALES', border=1,  align='C', fill=True, ln=1)
        pdf.set_font('Arial', '', 8)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=5,txt='Nombre Completo:', border='TRL', align='L', fill=False)
        pdf.cell(w=49,h=5,txt='Código del Cliente:', border='TRL', align='L', fill=False , ln=1)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=147,h=5,txt= cdg.NombreConzCli if hasattr(cdg, 'NombreConzCli') else '' , border='BLR', align='C', fill=False)
        pdf.cell(w=49,h=5,txt=cdg.Codigo if hasattr(cdg, 'Codigo') else '', border='BLR', align='C', fill=False, ln=1 )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=8,txt='Calidad en la que Actúa: ' , border=1, align='L', fill=False)
        pdf.set_xy(50, 55)
        if cdg.CalidadActu=='Cliente':
           
            pdf.cell(w=30,h=10,txt='Cliente', border=0,  align='L', fill=0)
            pdf.set_xy(64, 58)
            pdf.cell(w=4,h=4,txt='X', border=1,  align='L', fill=0)
            pdf.set_xy(75, 55)
            pdf.cell(w=20,h=10,txt='Fiador', border=0,  align='L', fill=0)
            pdf.set_xy(90, 58)
            pdf.cell(w=4,h=4,txt='', border=1,  align='L', fill=0)
            pdf.cell(w=62, h=5, border=0)
        else:
            
            pdf.cell(w=30,h=10,txt='Cliente', border=0,  align='L', fill=0)
            pdf.set_xy(64, 58)
            pdf.cell(w=4,h=4,txt='', border=1,  align='L', fill=0)
            pdf.set_xy(75, 55)
            pdf.cell(w=20,h=10,txt='Fiador', border=0,  align='L', fill=0)
            pdf.set_xy(90, 58)
            pdf.cell(w=4,h=4,txt='X', border=1,  align='L', fill=0)
            pdf.cell(w=62, h=5, border=0)
        pdf.set_xy(157,56)
        pdf.cell(w=20,h=8,txt='Estado Civil: ', border='LTB', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        if cdg.CalidadActu == "Cliente":
            pdf.multi_cell(w=0,h=8,txt= dp.EstadoCiviCli if hasattr(dp, 'EstadoCiviCli') else '', border='RTB', align='L', fill=False)
        elif cdg.CalidadActu == "Fiador":
            pdf.multi_cell(w=0,h=8,txt= dpc.EstadoCiviFiad if hasattr(dpc, 'EstadoCiviFiad') else '', border='RTB', align='L', fill=False)
        else:
            pdf.multi_cell(w=0,h=8,txt= '', border='RTB', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=5,txt='Conocido por: (Solo si lo dice el DUI)', border='TRL', align='L', fill=False)
        pdf.multi_cell(w=0,h=5,txt='Profesión según DUI:', border='TRL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=147,h=5,txt=cdg.ConocidoComo if hasattr(cdg, 'ConocidoComo') else '', border='BLR', align='C', fill=False)
        if cdg.CalidadActu == "Cliente":
            pdf.multi_cell(w=49,h=5,txt=perf.IdOcupacionDUI.Nombre if hasattr(perf, 'IdOcupacionDUI') else '', border='BLR', align='C', fill=False)
        elif cdg.CalidadActu == "Fiador":
           pdf.multi_cell(w=49,h=5,txt=dpc.IdOcupacionDUIFia.Nombre if hasattr(dpc, 'IdOcupacionDUIFia') else '', border='BLR', align='C', fill=False)
        else:
            pdf.multi_cell(w=49,h=5,txt= '', border='RTB', align='L', fill=False)
        
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=5,txt='Lugar y fecha de nacimiento:', border='TRL', align='L', fill=False)
        pdf.cell(w=49,h=5,txt='Nacionalidad:', border='TRL', align='L', fill=False , ln=1)
        pdf.set_text_color(0,0,0)
        if cdg.CalidadActu == "Cliente":
            pdf.cell(w=147,h=5,txt= (dp.LugarDuiCli if hasattr(dp, 'LugarDuiCli') else '')+', '+ (perf.FechaNaci.strftime("%d/%m/%Y") if hasattr(perf, 'FechaNaci') else ''), border='BLR', align='C', fill=False)
        elif cdg.CalidadActu == "Fiador":
            pdf.cell(w=147,h=5,txt= (dpc.LugarNaciFia if hasattr(dpc, 'LugarNaciFia') else '')+', '+ (dpc.FechaNaciFia.strftime("%d/%m/%Y") if hasattr(dpc, 'FechaNaciFia') else ''), border='BLR', align='C', fill=False)
        else:
            pdf.cell(w=147,h=5,txt= '', border='BLR', align='C', fill=False)
        pdf.cell(w=49,h=5,txt=cdg.Nacionalidad if hasattr(cdg, 'Nacionalidad') else '', border='BLR', align='C', fill=False, ln=1 )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=45,h=5,txt='Documento de Identidad:', border='TRL', align='L', fill=False)
        pdf.cell(w=43,h=5,txt='No. Documento:', border='TRL', align='L', fill=False)
        pdf.cell(w=59,h=5,txt='Fecha de Vencimiento:', border='TRL', align='L', fill=False)
        pdf.multi_cell(w=0,h=5,txt='Ocupación o Actividad actual:', border='TRL', align='L', fill=False)
        pdf.cell(w=45,h=5,txt='', border='BLR', align='C', fill=False)
        pdf.set_xy(10, 88)
        if cdg.DocumentoIden=='DUI':
           
            pdf.cell(w=8,h=5,txt='DUI', border=0,  align='L', fill=0)
            pdf.set_xy(17, 89)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(25, 88)
            pdf.cell(w=8,h=5,txt='PAS', border=0,  align='L', fill=0)
            pdf.set_xy(33, 89)
            pdf.cell(w=3,h=3,txt='', border=1,  align='L', fill=0)
            pdf.set_xy(38, 88)
            pdf.cell(w=7,h=5,txt='CR', border=0,  align='C', fill=0)
            pdf.set_xy(45, 89)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            

        elif cdg.DocumentoIden=='PAS':
           
            pdf.cell(w=8,h=5,txt='DUI', border=0,  align='L', fill=0)
            pdf.set_xy(17, 89)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(25, 88)
            pdf.cell(w=8,h=5,txt='PAS', border=0,  align='L', fill=0)
            pdf.set_xy(33, 89)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='L', fill=0)
            pdf.set_xy(38, 88)
            pdf.cell(w=7,h=5,txt='CR', border=0,  align='C', fill=0)
            pdf.set_xy(45, 89)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            
        else:
            
            pdf.cell(w=8,h=5,txt='DUI', border=0,  align='L', fill=0)
            pdf.set_xy(17, 89)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(25, 88)
            pdf.cell(w=8,h=5,txt='PAS', border=0,  align='L', fill=0)
            pdf.set_xy(33, 89)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='L', fill=0)
            pdf.set_xy(38, 88)
            pdf.cell(w=7,h=5,txt='CR', border=0,  align='C', fill=0)
            pdf.set_xy(45, 89)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)

        pdf.set_text_color(0,0,0)   
        pdf.set_xy(55,89)
        pdf.cell(w=43,h=5,txt=cdg.NumeroDocu if hasattr(cdg, 'NumeroDocu') else '', border='BLR', align='C', fill=False)
        pdf.cell(w=59,h=5,txt=cdg.FechaVencdoc.strftime("%d/%m/%Y") if hasattr(cdg, 'FechaVencdoc') else '', border='BLR', align='C', fill=False)
        if cdg.CalidadActu == "Cliente":
            pdf.multi_cell(w=0,h=5,txt=perf.IdOcupacion.Nombre if hasattr(perf, 'IdOcupacion') else '', border='BLR', align='C', fill=False)
        elif cdg.CalidadActu == "Fiador":
            pdf.multi_cell(w=0,h=5,txt=dpc.IdOcupacionFia.Nombre if hasattr(dpc, 'IdOcupacionFia') else '', border='BLR', align='C', fill=False)
        else:
            pdf.multi_cell(w=0,h=5,txt='', border='BLR', align='C', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=45,h=5,txt='N° de NIT:', border='TRL', align='L', fill=False)
        pdf.cell(w=43,h=5,txt='No. Registro de IVA:', border='TRL', align='L', fill=False)
        pdf.cell(w=59,h=5,txt='Correo Electrónico:', border='TRL', align='L', fill=False)
        pdf.cell(w=27,h=5,txt='Teléfono de Celular: ', border='TL', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        if cdg.CalidadActu == "Cliente":
            pdf.cell(w=22,h=5,txt= perf.Telefono if hasattr(perf, 'Telefono') else '', border='TR', align='L', fill=False , ln=1)
        elif cdg.CalidadActu == "Fiador":
            pdf.multi_cell(w=0,h=5,txt=cdg.TelefonoCelu if hasattr(cdg, 'TelefonoCelu') else '', border='BLR', align='C', fill=False)
        else:
            pdf.cell(w=22,h=5,txt= '', border='TR', align='L', fill=False , ln=1)
        pdf.cell(w=45,h=5,txt='--------------------', border='BLR', align='C', fill=False)
        pdf.cell(w=43,h=5,txt='--------------------', border='BLR', align='C', fill=False)       
        pdf.cell(w=59,h=5,txt=cdg.CorreoElec if hasattr(cdg, 'CorreoElec') else '', border='BLR', align='C', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=21,h=5,txt='Teléfono Fijo :', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=28,h=5,txt=cdg.TelefonoFijo if hasattr(cdg, 'TelefonoFijo') else '', border='BR', align='L', fill=False, ln=1 )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=5,txt='Dirección domicilio:', border='TRL', align='L', fill=False)
        pdf.cell(w=49,h=5,txt='Tiempo de residir en esta dirección:', border='TRL', align='L', fill=False , ln=1)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=147,h=5,txt=cdg.DireccionDomi if hasattr(cdg, 'DireccionDomi') else '', border='BLR', align='C', fill=False)
        pdf.cell(w=49,h=5,txt=d.ResideDesd if hasattr(d, 'ResideDesd') else '', border='BLR', align='C', fill=False, ln=1 )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=37,h=5,txt='Giro, según tarjeta de IVA: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=110,h=5,txt=' --------------------------------------------', border='BR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=31,h=5,txt='Estatus de la propiedad:  ', border='BL', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.cell(w=18,h=5,txt= cdg.EstatusProp if hasattr(cdg, 'EstatusProp') else '', border='BR', align='L', fill=False , ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=30,h=5,txt='Nombre del Cónyuge:  ', border='LTB', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt=cdg.NombreCony if hasattr(cdg, 'NombreCony') else '', border='TRB', align='L', fill=False, ln=1)
        pdf.set_text_color(255,255,255)
        pdf.multi_cell(w=0,h=6,txt='ACTIVIDADES ECONOMICAS DEL CLIENTE', border=1,  align='C', fill=True)
        pdf.set_text_color(r,g,b)
        pdf.multi_cell(w=0,h=5,txt='', border=1, align='L', fill=False)
        pdf.set_xy(10, 130)

        if cdaec!="" and cdaec.TipoActi=='Empleado':
           
            pdf.cell(w=20,h=5,txt='Empleado', border=0,  align='L', fill=0)
            pdf.set_xy(25, 131)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(35, 130)
            pdf.cell(w=20,h=5,txt='Negocio Propio', border=0,  align='L', fill=0)
            pdf.set_xy(60, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='L', fill=0)
            pdf.set_xy(70, 130)
            pdf.cell(w=15,h=5,txt='Dependiente', border=0,  align='C', fill=0)
            pdf.set_xy(90, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(100, 130)
            pdf.cell(w=10,h=5,txt='Otro', border=0,  align='C', fill=0)
            pdf.set_xy(110, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 130)
            pdf.multi_cell(w=0,h=5, txt='', border=0)

        elif cdaec!="" and cdaec.TipoActi=='Negocio Propio':
           
            pdf.cell(w=20,h=5,txt='Empleado', border=0,  align='L', fill=0)
            pdf.set_xy(25, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(35, 130)
            pdf.cell(w=20,h=5,txt='Negocio Propio', border=0,  align='L', fill=0)
            pdf.set_xy(60, 131)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='L', fill=0)
            pdf.set_xy(70, 130)
            pdf.cell(w=15,h=5,txt='Dependiente', border=0,  align='C', fill=0)
            pdf.set_xy(90, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(100, 130)
            pdf.cell(w=10,h=5,txt='Otro', border=0,  align='C', fill=0)
            pdf.set_xy(110, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 130)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        elif cdaec!="" and cdaec.TipoActi=='Dependiente':
           
            pdf.cell(w=20,h=5,txt='Empleado', border=0,  align='L', fill=0)
            pdf.set_xy(25, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(35, 130)
            pdf.cell(w=20,h=5,txt='Negocio Propio', border=0,  align='L', fill=0)
            pdf.set_xy(60, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='L', fill=0)
            pdf.set_xy(70, 130)
            pdf.cell(w=15,h=5,txt='Dependiente', border=0,  align='C', fill=0)
            pdf.set_xy(90, 131)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(100, 130)
            pdf.cell(w=10,h=5,txt='Otro', border=0,  align='C', fill=0)
            pdf.set_xy(110, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 130)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            
            pdf.cell(w=20,h=5,txt='Empleado', border=0,  align='L', fill=0)
            pdf.set_xy(25, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(35, 130)
            pdf.cell(w=20,h=5,txt='Negocio Propio', border=0,  align='L', fill=0)
            pdf.set_xy(60, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='L', fill=0)
            pdf.set_xy(70, 130)
            pdf.cell(w=15,h=5,txt='Dependiente', border=0,  align='C', fill=0)
            pdf.set_xy(90, 131)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(100, 130)
            pdf.cell(w=10,h=5,txt='Otro', border=0,  align='C', fill=0)
            pdf.set_xy(110, 131)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(85, 130)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        pdf.cell(w=40,h=5,txt='Especifique el lugar de trabajo: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= str(cdaec.LugarTrab) if hasattr(cdaec, 'LugarTrab') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=30,h=5,txt='cargo que desempeña: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=117,h=5,txt= cdaec.CargoDese if hasattr(cdaec, 'CargoDese') else '', border='BR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=26,h=5,txt='Tiempo de Laborar: ', border='BL', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.cell(w=23,h=5,txt=cdaec.TiempoLabo if hasattr(cdaec, 'TiempoLabo') else '', border='BR', align='L', fill=False , ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=36,h=5,txt='Procedencia de los Fondos: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= cdaec.ProcedenciaFond if hasattr(cdaec, 'ProcedenciaFond') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=52,h=5,txt='Rango Ingreso Mensual si es empleado: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=95,h=5,txt= cdaec.RangoIngrMen if hasattr(cdaec, 'RangoIngrMen') else '', border='BR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=20,h=5,txt='Otros Ingresos: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=29,h=5,txt= cdaec.OtrosIngr if hasattr(cdaec, 'OtrosIngr') else '', border='BR', align='L', fill=False, ln=1 )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=64,h=5,txt='De existir otros ingresos, describa la procedencia: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= cdaec.ProcedenciaOtroIng if hasattr(cdaec, 'ProcedenciaOtroIng') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='DATOS DEL NEGOCIO', border=1,  align='C', fill=True, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=30,h=5,txt='Nombre del negocio: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= cddn.NombreNego if hasattr(cddn, 'NombreNego') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=70,h=5,txt='Describa los productos y/o servicios que comercializa: ' , border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt=cddn.ProductoServ if hasattr(cddn, 'ProductoServ') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=30,h=5,txt='Dirección del negocio: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt=cddn.DireccionNego if hasattr(cddn, 'DireccionNego') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=40,h=5,txt='Fecha de inicio de actividades: ' , border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        if cddn.FechaInicAct == None:
            pdf.cell(w=36,h=5,txt='', border='BR', align='L', fill=False)
        else:
            pdf.cell(w=36,h=5,txt= (cddn.FechaInicAct.strftime("%d/%m/%Y") if hasattr(cddn, 'FechaInicAct') else ''), border='BR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=56,h=5,txt='Rango de ingresos mensuales del negocio: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=34,h=5,txt= cddn.RangoIngrMen if hasattr(cddn, 'RangoIngrMen') else '', border='BR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=21,h=5,txt='Otros ingresos: ', border='BL', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.cell(w=9,h=5,txt= cddn.OtrosIngrMen if hasattr(cddn, 'OtrosIngrMen') else '', border='BR', align='L', fill=False , ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=65,h=5,txt='De existir otros ingresos, describa la procedencia: ', border='BL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt=cddn.ProcedenciaOtroIng if hasattr(cddn, 'ProcedenciaOtroIng') else '', border='BR', align='L', fill=False, ln=1)
        pdf.set_text_color(255,255,255)
        pdf.multi_cell(w=196,h=6,txt='RECIBE REMESAS FAMILIARES', border=1,  align='C', fill=True)
        pdf.set_xy(145, 192)
        if cdrrfc != "" and str(cdrrfc.RecibeReme) =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(150, 193)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(160, 192)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(168, 193)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 192)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(150, 193)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(160, 192)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(168, 193)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(175, 192)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=75,h=5,txt='Nombre del remitente:', border=1, align='L', fill=False)
        pdf.cell(w=40,h=5,txt='Parentesco:', border=1, align='L', fill=False)
        pdf.cell(w=51,h=5,txt='Pais de origen:', border=1, align='L', fill=False)
        pdf.cell(w=30,h=5,txt='Monto:', border=1, align='L', fill=False , ln=1)

        pdf.set_text_color(0,0,0)
        if cdrrf!='' and len(cdrrf)>0:
            for rf in cdrrf:
                pdf.cell(w=75,h=5,txt=rf.NombreRemi or '', border=1,  align='L', fill=0)
                pdf.cell(w=40,h=5,txt=rf.Parentesco or '', border=1,  align='L', fill=0)
                pdf.cell(w=51,h=5,txt=rf.PaisOrig or '', border=1,  align='L', fill=0)
                pdf.cell(w=30,h=5,txt=str(rf.Monto) or '', border=1,  align='L', fill=0, ln=1)

        else:
            
            for i in aux:
                pdf.cell(w=75,h=5,txt='', border=1,  align='L', fill=0)
                pdf.cell(w=40,h=5,txt='', border=1,  align='L', fill=0)
                pdf.cell(w=51,h=5,txt='', border=1,  align='L', fill=0)
                pdf.cell(w=30,h=5,txt='', border=1,  align='L', fill=0, ln=1)


        
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='DECLARACIÓN DEL CLIENTE O FIADOR EN OPERACIONES ACTIVAS', border=1,  align='C', fill=True, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=81,h=5,txt='Clasificación del crédito: ', border=1, align='L', fill=False)
        pdf.set_xy(45, 213)
        if cdc!="" and cdc.ClasificacionCred=='Mejora':
            pdf.cell(w=5,h=5,txt='Mejora', border=0,  align='L', fill=0)
            pdf.set_xy(58, 214)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(65, 213)
            pdf.cell(w=5,h=5,txt='Vivienda', border=0,  align='L', fill=0)
            pdf.set_xy(80, 214)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)   
        elif cdc!="" and cdc.ClasificacionCred=='Vivienda':    
            pdf.cell(w=5,h=5,txt='Mejora', border=0,  align='L', fill=0)
            pdf.set_xy(58, 214)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(65, 213)
            pdf.cell(w=5,h=5,txt='Vivienda', border=0,  align='L', fill=0)
            pdf.set_xy(80, 214)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)      
        else:
            pdf.cell(w=5,h=5,txt='Mejora', border=0,  align='L', fill=0)
            pdf.set_xy(58, 214)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(65, 213)
            pdf.cell(w=5,h=5,txt='Vivienda', border=0,  align='L', fill=0)
            pdf.set_xy(80, 214)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            
        pdf.set_xy(91, 213)
        pdf.cell(w=20,h=5,txt='Monto: ', border='TBL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=35,h=5,txt=cdc.MontoDeclCli if hasattr(cdc, 'MontoDeclCli') else '', border='TBR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=20,h=5,txt='Cuota: ' , border='TBL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt=cdc.CuotaDeclCli if hasattr(cdc, 'CuotaDeclCli') else '', border='TBR', align='L', fill=False, ln=1)
        
        pdf.set_text_color(r,g,b)
        pdf.multi_cell(w=81,h=5,txt='Tiene proyectado realizar pagos  adicionales a las cuotas pactadas? ', border='LRT', align='L', fill=False)
        pdf.cell(w=81,h=10,txt='', border='LRB', align='L', fill=False)
        pdf.set_xy(25, 223)
        if  cdc!="" and cdc.RealizarPagoAdi =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(31, 224)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(40, 223)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(47, 224)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(60, 223)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(31, 224)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(40, 223)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(47, 224)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(60, 223)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        
        pdf.set_xy(91,218)
        pdf.cell(w=115,h=10,txt='Si su respuesta es afirmativa, indique la procedencia de los fondos: ', border='LTR', align='L', fill=False)
        pdf.set_xy(91,228)
        pdf.set_text_color(0,0,0)
        pdf.multi_cell(w=115,h=10,txt=cdc.ProcedenciaPagoAdi if hasattr(cdc, 'ProcedenciaPagoAdi') else '', border='LBR', align='L', fill=False)

        pdf.add_page()
        pdf.set_text_color(r,g,b)
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='PERSONA BENEFICIARIA DE LA OPERACIÓN       No Aplica', border=1,  align='C', fill=True, ln=1)
        
        if cdpbo!="" and cdpbo.NoApli =='No':                  
            pdf.set_xy(150, 11)
            pdf.cell(w=4,h=4,txt='X', border=1,  align='L', fill=True)
            pdf.cell(w=62, h=5, border=0)
        else:    
            pdf.set_xy(150, 11)
            pdf.cell(w=4,h=4,txt='', border=1,  align='L', fill=0)
            pdf.cell(w=62, h=5, border=0)

        pdf.set_text_color(r,g,b)
        pdf.cell(w=196,h=5,txt='En los casos que el préstamo sea para uso de otro beneficiario favor completar la siguiente información en todos sus campos sin excepción alguna:', border=1, align='L', fill=False, ln=1)
        pdf.cell(w=45,h=5,txt='Nombre completo del beneficiario:' , border='LTB', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.multi_cell(w=151,h=5,txt= str(cdpbo.NombreComp if hasattr(cdpbo,'NombreComp') else' --------------------------------------------------') or '--------------------------------------------------', border='TBR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=50,h=5,txt='Dirección permanente del beneficiario:', border='LTB', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=146,h=5,txt= (str(cdpbo.DireccionPerm if hasattr(cdpbo, 'DireccionPerm') else'     ---------------------------------------------') or '      ---------------------------------------------'), border='TBR', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=62,h=5,txt='Tipo y número de documento de indentificación:', border='LTB', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=134,h=5,txt=(str(cdpbo.TipoDocuPers if hasattr(cdpbo, 'TipoDocuPers') else'    -------------------------------------') or '      -------------------------------------')+', '+ (str(cdpbo.NumeroDocuPers if hasattr(cdpbo, 'NumeroDocuPers') else'    -------------------------------------') or '      -------------------------------------'), border='TRB', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=196,h=5,txt='El beneficiario es Persona Expuesta Politicamente:', border=1, align='L', fill=False, ln=1)

        pdf.set_xy(75, 31)
        if  cdpbo!="" and cdpbo.BeneficiarioPeps =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(80, 32)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(85, 31)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(92, 32)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(61, 31)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        elif  cdpbo!="" and cdpbo.BeneficiarioPeps =='No':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(80, 32)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 31)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(92, 32)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(60, 31)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(80, 32)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(85, 31)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(92, 32)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(60, 31)
            pdf.multi_cell(w=0,h=5, txt='', border=0)

        pdf.cell(w=196,h=5,txt='', border='BT', align='L', fill=False, ln=1)
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='PERFIL DE TRANSACCONES(PRODUCTOS ACTUALES CON LA ASOCIACIÓN)', border=1,  align='C', fill=True, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=20,h=5,txt='PRESTAMOS: ', border='LBT', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= cpt.Prestamos if hasattr(cpt, 'Prestamos') else '', border='RBT', align='L', fill=False, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=30,h=5,txt='Otros(especificar): ' , border='LBT', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=0,h=5,txt= cpt.EspecificarOtroPer if hasattr(cpt, 'EspecificarOtroPer') else '', border='RBT', align='L', fill=False, ln=1)
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='PERSONA EXPUESTA POLITICAMENTE(PEPs)', border=1,  align='C', fill=True, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=147,h=10,txt='¿Es usted una Persona Expuesta Politicamente(PEPs)?:', border=1, align='L', fill=False)
        
        pdf.set_xy(85, 66)
        if  cpeps!="" and cpeps.UstedPeps =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(93, 67)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(110, 66)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(118, 67)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(130, 67)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(93, 67)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(110, 66)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(118, 67)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(130, 67)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        

        pdf.set_xy(157, 63)
        pdf.cell(w=49,h=10,txt='PEPs POR PARENTESCO:', border=1, align='C', fill=False , ln=1)
        pdf.cell(w=147,h=10,txt='¿Tiene relación con alguna Persona Expuesta Politicamnete (PEPs)?:', border=1, align='L', fill=False)
        pdf.set_xy(120, 76)
        if  cpeps!="" and cpeps.RelacionPeps =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(128, 77)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(135, 76)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(143, 77)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(148, 77)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(128, 77)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(135, 76)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(143, 77)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(148, 77)
            pdf.multi_cell(w=0,h=5, txt='', border=0)
        

        pdf.set_xy(157, 73)
        pdf.cell(w=15,h=10,txt='Grado:', border=1, align='C', fill=False )
        pdf.cell(w=34,h=10,txt='Parentesco:', border=1, align='C', fill=False , ln=1)

        pdf.multi_cell(w=147,h=5,txt='¿Si su respuesta es afirmativa indique el nombre y/o parentesco de la Persona Expuesta Politicamente (PEPs)mcon la que tiene relacion y el puesto que desempeña?:', border=1, align='L', fill=False )
        pdf.set_xy(157,83)
        pdf.cell(w=15,h=10,txt='1er:', border=1, align='L', fill=False )
        pdf.set_xy(172,83)
        pdf.set_font('Arial', '', 7)
        if cpeps!="" and str(cpeps.Grado) =='Primero':
            print("hola")
            if cpeps!="" and str(cpeps.Parentesco) =='Padre': 
                pdf.cell(w=11,h=3,txt='Padre-', border="LBT", align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Madre':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border="BT", align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Suegro':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='BTR', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Suegra':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='BLRT', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Hijo':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border=1, align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Hija':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='BRLT', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Yerno':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='TR', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Nuera':
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='LRT', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
            else:
                pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
                pdf.set_xy(172,86)
                pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
                pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
                pdf.set_xy(172,89)
                pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
                pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )
        else:
            pdf.cell(w=11,h=3,txt='Padre-', border='L', align='L', fill=False )
            pdf.cell(w=11,h=3,txt='Madre-', border='', align='L', fill=False )
            pdf.multi_cell(w=0,h=3,txt='Suegro-', border='R', align='L', fill=False )
            pdf.set_xy(172,86)
            pdf.cell(w=11,h=3,txt='Suegra-', border='L', align='L', fill=False )
            pdf.cell(w=11,h=3,txt='Hijo-', border='', align='L', fill=False )
            pdf.multi_cell(w=0,h=3,txt='Hija-', border='R', align='L', fill=False )
            pdf.set_xy(172,89)
            pdf.cell(w=11,h=4,txt='Yerno-', border='', align='L', fill=False )
            pdf.cell(w=11,h=4,txt='Nuera', border='', align='L', fill=False )
            pdf.multi_cell(w=0,h=4,txt='', border='R', align='L', fill=False )

        pdf.set_font('Arial', '', 8)
        pdf.cell(w=13,h=5,txt='Nombre: ', border='L', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.cell(w=129,h=5,txt=cpeps.NombrePeps if hasattr(cpeps, 'NombrePeps') else '', border='BT', align='L', fill=False )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=5,h=5,txt=' ', border='T', align='L', fill=False )
        pdf.set_xy(157,93)
        pdf.cell(w=15,h=5,txt='', border='LR', align='L', fill=False, ln=1 )       
        pdf.cell(w=32,h=5,txt='Puesto que desempeña:', border='L', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.cell(w=110,h=5,txt=cpeps.PuestoDese if hasattr(cpeps, 'PuestoDese') else '', border='BT', align='L', fill=False )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=5,h=5,txt=' ', border='R', align='L', fill=False )
        pdf.set_xy(157,98)
        pdf.cell(w=15,h=5,txt='2er:', border='LR', align='L', fill=False , ln=1)
        pdf.cell(w=40,h=5,txt='Periodo de gestión:      Desde: ', border='BTL', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.cell(w=15,h=5,txt=(cpeps.PeriodoGestDes if hasattr(cpeps, 'PeriodoGestDes') else '') , border='BT', align='L', fill=False )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=15,h=5,txt='       Hasta:', border='BT', align='L', fill=False )
        pdf.set_text_color(0,0,0)
        pdf.multi_cell(w=0,h=5,txt=(cpeps.PeriodoGestHas if hasattr(cpeps, 'PeriodoGestHas') else ''), border='B', align='L', fill=False )
        pdf.set_text_color(r,g,b)
        pdf.set_xy(157,103)
        pdf.cell(w=15,h=5,txt='', border='LR', align='L', fill=False )
        pdf.set_xy(172,93)
        pdf.set_font('Arial', '', 7)
        if cpeps!="" and str(cpeps.Grado) =='Segundo':
            if cpeps!="" and str(cpeps.Parentesco) =='Abuelo': 
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LBT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Abuela':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='TB', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Hermano':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='T', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='BTR', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Hermana':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='T', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=12,h=4,txt='Hermana-', border='LBTR', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Cuñado':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=12,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='BTLR', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Cuñada':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='LBTR', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Nieto':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='BTR', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Nieta':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='LBTR', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Concuñado':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='LBTR', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
            elif cpeps!="" and str(cpeps.Parentesco) =='Abuelos del conyuge':
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='TR', align='L', fill=False )
            else:
                pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
                pdf.set_xy(172,97)
                pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
                pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
                pdf.set_xy(172,100)
                pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
                pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
                pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
                pdf.set_xy(172,104)
                pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )
        else:
            pdf.cell(w=10,h=4,txt='Abuelo-', border='LT', align='L', fill=False )
            pdf.cell(w=10,h=4,txt='Abuela-', border='T', align='L', fill=False )
            pdf.multi_cell(w=0,h=4,txt='Hermano-', border='RT', align='L', fill=False )
            pdf.set_xy(172,97)
            pdf.cell(w=11,h=4,txt='Hermana-', border='L', align='L', fill=False )
            pdf.cell(w=10,h=4,txt='Cuñado-', border='', align='L', fill=False )
            pdf.multi_cell(w=0,h=4,txt='Cuñada-', border='R', align='L', fill=False )
            pdf.set_xy(172,100)
            pdf.cell(w=9,h=4,txt='Nieto-', border='', align='L', fill=False )
            pdf.cell(w=9,h=4,txt='Nieta-', border='', align='L', fill=False )
            pdf.multi_cell(w=0,h=4,txt='Concuñado-', border='R', align='L', fill=False )
            pdf.set_xy(172,104)
            pdf.multi_cell(w=0,h=4,txt='Abuelos del conyuge', border='R', align='L', fill=False )

        pdf.set_font('Arial', '', 8)
        pdf.cell(w=10,h=5,txt=' YO: ', border='BTL', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.multi_cell(w=0,h=5,txt=cdg.NombreConzCli if hasattr(cdg, 'NombreConzCli') else '', border='BTR', align='L', fill=False)
        pdf.set_text_color(r,g,b)
        pdf.multi_cell(w=196,h=5,txt='Declaro bajo juramento que los datos antes descritos son verdaderos y que mis ingresos provienen de actividades enteramente licitas, por  consiguiente, dichos fondos no se encuentran relacionados bajo ninguna circunstancia con hechos o actividades criminales relacionadas con el  narcotráfico y delitos conexos con el Labado de Dinero y Activos, tampoco con situaciones en contra de la Ley Contra el Labado de Dinero y de  Activos de la Republica de El Salvador. Además declaro que me someto a cualquier tipo de investigación necesaria para establecer la procedencia y el  origen de los fondos de mi operación. Por último declaro que éste formulario ha sido completado por mi y/o en mi presencia y que la información provista  es verdadera. ' , border=1, align='L', fill=False)
        pdf.cell(w=4,h=10,txt='F: ', border='L', align='L', fill=False )
        pdf.cell(w=70,h=10,txt=' ', border='BT', align='L', fill=False )  
        pdf.cell(w=37,h=10,txt=' ', border='T', align='L', fill=False )     
        pdf.cell(w=20,h=10,txt='Lugar y Fecha: ', border='T', align='L', fill=False )
        pdf.cell(w=60,h=10,txt=' ', border='BT', align='L', fill=False )
        pdf.cell(w=5,h=10,txt=' ', border='TR', align='L', fill=False, ln=1 )
        pdf.cell(w=4,h=5,txt=' ', border='L', align='L', fill=False )
        pdf.cell(w=70,h=5,txt='Firma del Cliente ', border='', align='C', fill=False )  
        pdf.cell(w=37,h=5,txt=' ', border='', align='L', fill=False )     
        pdf.cell(w=20,h=5,txt='', border='', align='L', fill=False )
        pdf.cell(w=60,h=5,txt=' ', border='', align='L', fill=False )
        pdf.cell(w=5,h=5,txt=' ', border='R', align='L', fill=False, ln=1)
        pdf.cell(w=30,h=5,txt=' ', border='LB', align='L', fill=False )
        pdf.cell(w=18,h=5,txt='No. de Dui ', border='B', align='C', fill=False )  
        pdf.set_text_color(0,0,0)
        pdf.cell(w=25,h=5,txt=str(cdg.IdSolicitud.IdPerfil.Dui) if hasattr(cdg, 'IdSolicitud') else '', border='B', align='C', fill=False )
        pdf.set_text_color(r,g,b)
        pdf.cell(w=37,h=5,txt=' ', border='B', align='L', fill=False )     
        pdf.cell(w=20,h=5,txt=' ', border='B', align='L', fill=False )
        pdf.cell(w=60,h=5,txt=' ', border='B', align='L', fill=False )
        pdf.cell(w=0,h=5,txt=' ', border='RB', align='L', fill=False, ln=1 )
        pdf.set_text_color(255,255,255)
        pdf.cell(w=196,h=6,txt='PARA USO EXCLUSIVO DE ASOCIACIÓN HPH EL SALVADOR', border=1,  align='C', fill=True, ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=106,h=5,txt='CONFIRMACIÓN DE DATOS ', border='LRT', align='C', fill=False)
        pdf.cell(w=20,h=5,txt='Verificado por: ', border='L', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=70,h=5,txt=' '+ cpus.VerificadoPor if hasattr(cpus, 'VerificadoPor') else '', border='R', align='L', fill=False , ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=106,h=5,txt='¿Validé finmas, nombres y fotografía según documentos legales ? ', border='LR', align='C', fill=False)
        pdf.cell(w=30,h=5,txt='Código de empleado/a: ', border='L', align='L', fill=False)
        pdf.set_text_color(0,0,0)
        pdf.cell(w=60,h=5,txt=' '+ cpus.CodigoEmpl if hasattr(cpus, 'CodigoEmpl') else '' , border='R', align='L', fill=False , ln=1)
        pdf.set_text_color(r,g,b)
        pdf.cell(w=106,h=5,txt='' , border='LRB', align='C', fill=False)
        pdf.set_xy(40, 174)
        if  cpus!="" and cpus.ValideFirmNomFot =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(45, 175)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(55, 174)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(62, 175)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)

        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(45, 175)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(55, 174)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(62, 175)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(148, 77)   

        pdf.set_xy(116, 174)
        pdf.cell(w=90,h=5,txt='' , border='LRB', align='L', fill=False, ln=1)
        pdf.set_xy(10,178)
        pdf.multi_cell(w=106,h=6,txt='¿Verifiqué la dirección presentada con el documento de identidad personal,  coincide con la señalada por el cliente  ? ', border='LR', align='C', fill=False)
        pdf.set_xy(116,179)        
        pdf.multi_cell(w=0,h=5,txt='', border='LRT', align='C', fill=False)
        pdf.cell(w=106,h=5,txt='' , border='LR', align='L', fill=False)
        pdf.cell(w=5,h=5,txt='F. ' , border='L', align='L', fill=False )
        pdf.cell(w=80,h=5,txt='' , border='B', align='L', fill=False )
        pdf.multi_cell(w=0,h=5,txt='' , border='R', align='L', fill=False)
        pdf.cell(w=106,h=5,txt='', border='LR', align='C', fill=False)
        pdf.cell(w=90,h=5,txt='Firma del Ejecutivo' , border='LR', align='C', fill=False, ln=1)
        pdf.cell(w=106,h=5,txt='', border='LRB', align='C', fill=False)
        pdf.set_xy(40, 191)
        if  cpus!="" and cpus.VerifiqueDire =='Si':
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(45, 192)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            pdf.set_xy(55, 191)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(62, 192)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
        else:
            pdf.cell(w=5,h=5,txt='SI', border=0,  align='L', fill=0)
            pdf.set_xy(45, 192)
            pdf.cell(w=3,h=3,txt='', border=1,  align='C', fill=0)
            pdf.set_xy(55, 191)
            pdf.cell(w=5,h=5,txt='NO', border=0,  align='L', fill=0)
            pdf.set_xy(62, 192)
            pdf.cell(w=3,h=3,txt='X', border=1,  align='C', fill=0)
            #pdf.set_xy(148, 77)
            #pdf.multi_cell(w=0,h=5, txt='', border=0)
        

        pdf.set_xy(116, 194)
        pdf.cell(w=90,h=5,txt='' , border='LRB', align='L', fill=False)
       
     
        pdf.output('ConozcaCliente.pdf', 'F')
        return FileResponse(open('ConozcaCliente.pdf', 'rb'), as_attachment=True, content_type='application/pdf')
