from fpdf import FPDF
from datetime import date
import locale
from termcolor import colored
from django.http import FileResponse
from EvaluacionMicroApp.models import *


class evaluacionIM(FPDF):
    
    def evaluacionMc(request, id ):
        locale.setlocale(locale.LC_TIME, '')
        fecha=date.today()

        ide=int(id)
        try:    
            egm=  EgresoFlujMic.objects.get(Id=ide)
        except EgresoFlujMic.DoesNotExist:
            egm="" 
        try:    
            blm=  BalanceSituMic.objects.get(Id=egm.IdBalanceSituMic.Id)
        except BalanceSituMic.DoesNotExist:
            blm="" 

        try:    
            atm=  ActivoBalaSit.objects.get(IdBalanceSituMic=egm.IdBalanceSituMic.Id)
        except ActivoBalaSit.DoesNotExist:
            atm=""
        try:    
            psm=  PasivoBalaSit.objects.get(IdBalanceSituMic=egm.IdBalanceSituMic.Id)
        except PasivoBalaSit.DoesNotExist:
            psm=""
        try:    
            etm=  EstadoResuMic.objects.get(IdBalanceSituMic=egm.IdBalanceSituMic.Id)
        except EstadoResuMic.DoesNotExist:
            etm="" 

        try: 
            cliente = Perfil.objects.get(Id=egm.IdBalanceSituMic.IdPerfil.Id)
        except Perfil.DoesNotExist:
            cliente=""        
        try:    
            igm=  IngresoFlujMic.objects.get(IdEgresoFlujMic=ide)
        except IngresoFlujMic.DoesNotExist:
            igm="" 
        try:    
            cpm=  CapacidadPagoMic.objects.get(IdEgresoFlujMic=ide)
        except CapacidadPagoMic.DoesNotExist:
            cpm="" 


        r=59
        g=93
        b=149
        aux=[0, 1, 2, 3]
        aux2=[0, 1, 2]    
        pdf=FPDF(orientation='P', unit='mm', format='Letter')
        pdf.add_page()
        #pdf.multi_cell(w=0, h=40, txt='', border=1)
        
        pdf.set_font('Arial', 'B', 12)
        #pdf.set_fill_color(r,g,b)
        #pdf.set_text_color(255,255,255)
        pdf.image('TesisApp/static/TesisApp/images/logohabitat.jpg', x=8, y=5, w=45, h=30)#, link=url) 
        pdf.set_font('Arial', 'B', 12)
        pdf.set_y(30)
        pdf.set_left_margin(10)       
        pdf.cell(w=184,h=8,txt='EVALUACIÓN PARA MICROEMPRESARIOS', border=1,  align='C', fill=False, ln=1)
        pdf.cell(w=184,h=4,txt='', border='TB',  align='C', fill=False, ln=1)  
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(w=184,h=6,txt='Tipo de Negocio: ' + blm.TipoNego if hasattr(blm, 'TipoNego') else '', border=1,  align='L', fill=False, ln=1)
        pdf.cell(w=184,h=4,txt='', border=1,  align='C', fill=False, ln=1)       
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(w=20,h=6,txt='Solicitante: ' , border='', align='L', fill=False)
        pdf.set_fill_color(217,217,217)
        pdf.cell(w=164,h=6,txt= (cliente.Nombres if hasattr(cliente, 'Nombres') else '') +' '+ (cliente.Apellidos if hasattr(cliente, 'Apellidos') else '') , border='BT', align='L', fill=True, ln=1)
        pdf.cell(w=184,h=4,txt='', border=1, align='L', fill=False, ln=1)
        pdf.set_fill_color(217,217,217)
        pdf.cell(w=184,h=5,txt='Balance de Situación', border=1, align='C', fill=True, ln=1)
        pdf.cell(w=55,h=5,txt='Circulante', border=1, align='C', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(atm.TotalCircAct) if hasattr(atm, 'TotalCircAct') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=79,h=5,txt='Circulante', border=1, align='C', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(psm.TotalCircPas) if hasattr(psm, 'TotalCircPas') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=55,h=5,txt='Caja', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(atm.Caja) if hasattr(atm, 'Caja') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=79,h=5,txt='Proveedores', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(psm.Proveedores) if hasattr(psm, 'Proveedores') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.cell(w=55,h=5,txt='Bancos', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(atm.Bancos) if hasattr(atm, 'Bancos') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=79,h=5,txt='Cuentas por Pagar', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(psm.CuentasPorPag) if hasattr(psm, 'CuentasPorPag') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.cell(w=55,h=5,txt='Cuentas por Cobrar', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(atm.CuentasPorCob) if hasattr(atm, 'CuentasPorCob') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=79,h=5,txt='Préstamos a 1 año', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(psm.PrestamosCortPla) if hasattr(psm, 'PrestamosCortPla') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.cell(w=55,h=5,txt='Inventarios', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(atm.Inventarios) if hasattr(atm, 'Inventarios') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=79,h=5,txt='', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt='', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(w=55,h=5,txt='Fijo', border=1, align='C', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(atm.TotalFijoAct) if hasattr(atm, 'TotalFijoAct') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=79,h=5,txt='Fijo', border=1, align='C', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(psm.FijoPasi) if hasattr(psm, 'FijoPasi') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=55,h=5,txt='Mobiliario', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(atm.Mobiliario) if hasattr(atm, 'Mobiliario') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=79,h=5,txt='Préstamos a Largo Plazo', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(psm.PrestamosLargPla) if hasattr(psm, 'PrestamosLargPla') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.cell(w=55,h=5,txt='Terrenos', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(atm.Terrenos) if hasattr(atm, 'Terrenos') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=79,h=5,txt='Total Pasivo', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(psm.TotalPasi) if hasattr(psm, 'TotalPasi') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.cell(w=55,h=5,txt='Vehículos', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(atm.Vehiculos) if hasattr(atm, 'Vehiculos') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=79,h=5,txt='Patrimonio', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(psm.Patrimonio) if hasattr(psm, 'Patrimonio') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.cell(w=55,h=5,txt='', border='LBT', align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt='', border='RBT',  align='R', fill=False)
        pdf.cell(w=79,h=5,txt='Capital', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=20,h=5,txt=str(psm.Capital) if hasattr(psm, 'Capital') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.cell(w=184,h=5,txt='', border=1, align='L', fill=False, ln=1)
        pdf.set_fill_color(191,191,191)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(w=55,h=5,txt='Total Activo', border='LBT', align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=True)
        pdf.cell(w=20,h=5,txt=str(atm.TotalActi) if hasattr(atm, 'TotalActi') else '0', border='RBT',  align='R', fill=True)
        pdf.cell(w=79,h=5,txt='Pasivo + Patrimpnio', border=1, align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=True)
        pdf.cell(w=20,h=5,txt=str(psm.PasivoMasPat) if hasattr(psm, 'PasivoMasPat') else '0', border='RBT',  align='R', fill=True)
        pdf.cell(w=0,h=5,txt='', border='L', align='L', fill=False, ln=1)
        pdf.cell(w=184,h=5,txt='', border=1, align='L', fill=False, ln=1)
        
        
        pdf.set_fill_color(191,191,191)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=48,h=6,txt='Estado de Resultados', border=1,  align='C', fill=True)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(w=136,h=6,txt='Flujo de Caja', border=1,  align='C', fill=True, ln=1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=30,h=5,txt='Ventas Totales', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.VentasTota) if hasattr(etm, 'VentasTota') else '0', border='RBT',  align='R', fill=False)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(w=88,h=5,txt='Egresos', border=1,  align='C', fill=True)
        pdf.cell(w=48,h=5,txt='Ingresos', border=1,  align='C', fill=True, ln=1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=30,h=5,txt='Ventas Totales', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.VentasTota) if hasattr(etm, 'VentasTota') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=70,h=5,txt='Alimentación del grupo familiar', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.Alimentacion) if hasattr(egm, 'Alimentacion') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=30,h=5,txt='Negocio', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(igm.Negocio) if hasattr(igm, 'Negocio') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L',  align='L', fill=False, ln=1)
        pdf.cell(w=30,h=5,txt='', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt='', border='RBT',  align='R', fill=False)
        pdf.cell(w=70,h=5,txt='Educación del grupo familiar', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.Educacion) if hasattr(egm, 'Educacion') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=30,h=5,txt='Remesas', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(igm.Remesas) if hasattr(igm, 'Remesas') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L',  align='L', fill=False, ln=1)
        pdf.cell(w=30,h=5,txt='Costo de Ventas', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.CostoVent) if hasattr(etm, 'CostoVent') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=70,h=5,txt='Transporte', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.Transporte) if hasattr(egm, 'Transporte') else '0', border='RBT',  align='R', fill=False)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(w=30,h=5,txt='Total(2)', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(igm.TotalIngrMic) if hasattr(igm, 'TotalIngrMic') else '0', border='RBT',  align='R', fill=False)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=0,h=5,txt='', border='L',  align='L', fill=False, ln=1)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(w=30,h=5,txt='Utilidad Bruta', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.UtilidadBrut) if hasattr(etm, 'UtilidadBrut') else '0', border='RBT',  align='R', fill=False)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=70,h=5,txt='Salud / ISSS / ISBM / Otros gastos de salud', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.Salud) if hasattr(egm, 'Salud') else '0', border='RBT',  align='R', fill=False)
        pdf.set_fill_color(191,191,191)
        pdf.set_font('Arial', 'B', 8)
        pdf.cell(w=48,h=5,txt='Análisis de Capacidad de Pago', border=1,  align='C', fill=True)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=0,h=5,txt='%', border=1,  align='C', fill=False, ln=1)
        #pdf.set_font('Arial', '', 9)
        pdf.cell(w=30,h=5,txt='Gastos Grales.', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.GastosGral) if hasattr(etm, 'GastosGral') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=70,h=5,txt='AFP / IPSFA / IRS / Otros', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.Afp) if hasattr(egm, 'Afp') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=48,h=5,txt='Endeudamiento Actual:', border=1,  align='C', fill=False)
        pdf.set_fill_color(155,187,89)
        pdf.set_font('Arial', '', 8)
        pdf.cell(w=0,h=5,txt=str(cpm.PorcentajeEnde) if hasattr(cpm, 'PorcentajeEnde') else '0.0%', border=1,  align='C', fill=True, ln=1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=30,h=5,txt='Transporte', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.Transporte) if hasattr(etm, 'Transporte') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=70,h=5,txt='Servicios', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.Servicios) if hasattr(egm, 'Servicios') else '0', border='RBT',  align='R', fill=False)
        pdf.set_fill_color(191,191,191)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(w=30,h=5,txt='Disponible = 2-1', border=1,  align='C', fill=True)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=18,h=5,txt='', border='LRT',  align='L', fill=False)
        pdf.set_fill_color(155,187,89)
        pdf.cell(w=0,h=5,txt='', border='LRT',  align='L', fill=True, ln=1)
        pdf.cell(w=30,h=5,txt='Servicios', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.Servicios) if hasattr(etm, 'Servicios') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=70,h=5,txt='Alquiler', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.Alquiler) if hasattr(egm, 'Alquiler') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=30,h=5,txt='Ingresos - Egresos', border=1,  align='C', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='B',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(cpm.Disponible) if hasattr(cpm, 'Disponible') else '0', border='RB',  align='R', fill=False)
        pdf.set_fill_color(155,187,89)
        pdf.set_font('Arial', '', 8)
        pdf.cell(w=0,h=5,txt=str(cpm.PorcentajeDisp) if hasattr(cpm, 'PorcentajeDisp') else '0', border='LRB',  align='C', fill=True, ln=1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=30,h=5,txt='Impuestos', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.Impuestos) if hasattr(etm, 'Impuestos') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=35,h=5,txt='', border='LRT',  align='L', fill=False)
        pdf.set_fill_color(217,217,217)
        pdf.cell(w=35,h=5,txt='En Planilla', border=1,  align='L', fill=True)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.PorcentajePlan) if hasattr(egm, 'PorcentajePlan') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=30,h=5,txt='Cuota', border=1,  align='C', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(cpm.Cuota) if hasattr(cpm, 'Cuota') else '0', border='RBT',  align='R', fill=False)
        pdf.set_fill_color(155,187,89)
        pdf.set_font('Arial', '', 8)
        pdf.cell(w=0,h=5,txt=str(cpm.PorcentajeCuot) if hasattr(cpm, 'PorcentajeCuot') else '0', border=1,  align='C', fill=True, ln=1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=30,h=5,txt='Alquiler', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.Alquiler) if hasattr(etm, 'Alquiler') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=35,h=5,txt='Préstamos Actuales', border='LR',  align='C', fill=False)
        pdf.set_fill_color(217,217,217)
        pdf.cell(w=35,h=5,txt='En Ventanilla', border=1,  align='L', fill=True)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.PorcentajeVent) if hasattr(egm, 'PorcentajeVent') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=30,h=5,txt='Superávit', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(cpm.Superavit) if hasattr(cpm, 'Superavit') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L',  align='L', fill=False, ln=1)
        pdf.cell(w=30,h=5,txt='Cuota Préstamos', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.CuotaPres) if hasattr(etm, 'CuotaPres') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=35,h=5,txt='', border='LRB',  align='L', fill=False)
        pdf.set_fill_color(217,217,217)
        pdf.cell(w=35,h=5,txt='HPH EL SALVADOR', border=1,  align='L', fill=True)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.PorcentajeHplhes) if hasattr(egm, 'PorcentajeHplhes') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=30,h=5,txt='Deficit', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(cpm.Deficit) if hasattr(cpm, 'Deficit') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L',  align='L', fill=False, ln=1)
        pdf.cell(w=30,h=5,txt='Imprevistos', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.ImprevistosEstaRes) if hasattr(etm, 'ImprevistosEstaRes') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=70,h=5,txt='Otros descuentos', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.OtrosDesc) if hasattr(egm, 'OtrosDesc') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L',  align='L', fill=False, ln=1)
        pdf.cell(w=30,h=5,txt='Utilidad Neta', border=1,  align='L', fill=False)
        pdf.set_fill_color(191,191,191)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=True)
        pdf.cell(w=13,h=5,txt=str(etm.UtilidadNeta) if hasattr(etm, 'UtilidadNeta') else '0', border='RBT',  align='R', fill=True)
        pdf.cell(w=70,h=5,txt='Recreación', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.Recreacion) if hasattr(egm, 'Recreacion') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L',  align='L', fill=False, ln=1)
        pdf.cell(w=30,h=5,txt='Mensual', border='',  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(etm.Mensual) if hasattr(etm, 'Mensual') else '0', border='',  align='R', fill=False)
        pdf.cell(w=70,h=5,txt='Imprevistos', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.Imprevistos) if hasattr(egm, 'Imprevistos') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L',  align='L', fill=False, ln=1)
        pdf.cell(w=30,h=5,txt='', border='',  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='', border='',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt='', border='',  align='R', fill=False)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(w=70,h=5,txt='Total(1)', border=1,  align='L', fill=False)
        pdf.cell(w=5,h=5,txt='$', border='LBT',  align='L', fill=False)
        pdf.cell(w=13,h=5,txt=str(egm.Total) if hasattr(egm, 'Total') else '0', border='RBT',  align='R', fill=False)
        pdf.cell(w=0,h=5,txt='', border='L',  align='L', fill=False, ln=1)

        pdf.cell(w=184,h=20,txt='', border='',  align='C', fill=False, ln=1)
        pdf.set_font('Arial', '', 10)
        pdf.cell(w=126,h=5,txt='', border='',  align='R', fill=False)
        pdf.cell(w=30,h=5,txt='Presentado por: ', border='',  align='L', fill=False)
        pdf.cell(w=0,h=5,txt='', border='B',  align='L', fill=False, ln=1)
        pdf.cell(w=126,h=5,txt='', border='',  align='R', fill=False)
        pdf.cell(w=30,h=5,txt='', border='',  align='L', fill=False)
        pdf.set_font('Arial', 'B', 8)
        pdf.cell(w=0,h=5,txt='Nombre del Oficial de Crédito', border='T',  align='L', fill=False, ln=1)


     
        pdf.output('evaluacionMicroempresa.pdf', 'F')
        return FileResponse(open('evaluacionMicroempresa.pdf', 'rb'), as_attachment=True, content_type='application/pdf')
        #return redirect("listaSolicitud")
