"""
Django settings for Tesis project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z)=ccz49)i9pp5f)^g(gfp76d-_1t^nru1fevpj&txk7fd&q*e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

MESSAGE_STORAGE="django.contrib.messages.storage.cookie.CookieStorage"
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',  
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  
    'django.contrib.sites', # Sirve para enviar correos
    'TesisApp',# agredar siempre las app aqui
    'DireccionApp',
    'ClienteApp',
    'ConfiguracionApp',
    'SolicitudesApp',
    'ConozcaClienteApp',
    'NaturalApp',
    'DeclaracionJurClienteApp',
    'SolicitudInscripcionSApp',
    'InspeccionLoteApp',
    'GraficasApp',
    'Reportes',
    'HistorialApp',
    'PresupuestoApp',
    'PresupuestoVApp',
    'InspeccionMejViviendaApp',
    'EvaluacionIvEFApp',
    'EvaluacionMicroApp',
    'ListaChequeoApp',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'Tesis.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': ['/app/TesisApp/Templates/',
                 '/app/DireccionApp/Templates/',
                 '/app/ClienteApp/Templates/',
    '/app/ConfiguracionApp/Templates/',
    '/app/SolicitudesApp/Templates/',
    '/app/ConozcaClienteApp/Templates/',
    '/app/NaturalApp/Templates/',
    '/app/DeclaracionJurClienteApp/Templates/',
    '/app/SolicitudInscripcionSApp/Templates/',
    '/app/InspeccionLoteApp/Templates/',
    '/app/GraficasApp/Templates/',
    '/app/Reportes/Templates/',
    '/app/HistorialApp/Templates/',
    '/app/PresupuestoApp/Templates/',
    '/app/PresupuestoVApp/Templates/',
    '/app/InspeccionMejViviendaApp/Templates/',
    '/app/EvaluacionIvEFApp/Templates/',
    '/app/EvaluacionMicroApp/Templates/',
    '/app/ListaChequeoApp/Templates/',],
       # 'DIRS': [os.path.join(BASE_DIR, 'DireccionApp','Templates')],
        "APP_DIRS": True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tesis.wsgi.application'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE="whitenoise.storage.CompressedManifestStaticFilesStorage"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        'NAME': 'railway',
        'USER':'postgres',
        'PASSWORD':'mpooQvCPeKvbESUGbVJXkcxgMRXaQHZw',
        'HOST':'monorail.proxy.rlwy.net',
        'PORT':"24566",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-ni'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL='TesisApp.Usuario'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')

#LOGIN_REDIRECT_URL=''
#LOGOUT_REDIRECT_URL='/TesisApp/'
#LOGIN_URL='/TesisApp/'

SESSION_EXPIRE_SECONDS=1800
SESSION_EXPIRE_AFTER_LAST_ACTIVITY_GRACE_PERIOD = 5
SESSION_EXPIRE_AFTER_LAST_ACTIVITY=True

#####Correo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'duranroxa.10@gmail.com' #Validar en la configuracion del correo que permita acceder desde apps desconocidas para poder enviar el correo
EMAIL_HOST_PASSWORD = 'cwly xsbl bwlu wjfs' #Colocar la contraseña del correo o crear una contraseña para esta app
DOMAIN=''

