# Generated by Django 3.2.5 on 2024-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PresupuestoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='AsistenciaTecn',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='CancelarSaldPen',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='ComisionPorOto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='ConsultaBuroCre',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='Notas',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='PrimeraCuot',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='Total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='presupuestodatogen',
            name='DiasEstiCon',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='presupuestodatogen',
            name='MejoraReal',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='presupuestomanoobr',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestomanoobr',
            name='Descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='presupuestomanoobr',
            name='PrecioUnit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestomanoobr',
            name='SubTota',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='presupuestomanoobr',
            name='Unidad',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='presupuestomate',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestomate',
            name='PrecioUnit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestomate',
            name='SubTota',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='presupuestootro',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestootro',
            name='Descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='presupuestootro',
            name='PrecioUnit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestootro',
            name='SubTota',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='presupuestootro',
            name='Unidad',
            field=models.CharField(max_length=8),
        ),
    ]
