# Generated by Django 3.2.5 on 2024-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PresupuestoVApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestovividatgen',
            name='DimensionVivi',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='presupuestovividatgen',
            name='Modelo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='presupuestovividatgen',
            name='TiempoCons',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='presupuestovividatgenobr',
            name='CostoObra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovividatgenobr',
            name='SolucionSan',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivimanobr',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivimanobr',
            name='Descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='presupuestovivimanobr',
            name='PrecioUnit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivimanobr',
            name='SubTota',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='presupuestovivimanobr',
            name='Unidad',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='presupuestovivimanobrobr',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivimanobrobr',
            name='Descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='presupuestovivimanobrobr',
            name='PrecioUnit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivimanobrobr',
            name='SubTota',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='presupuestovivimat',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivimat',
            name='PrecioUnit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivimat',
            name='SubTota',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='presupuestovivimatobr',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivimatobr',
            name='PrecioUnit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivimatobr',
            name='SubTota',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='presupuestovivitot',
            name='Herramientas',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivitot',
            name='KitEmer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivitot',
            name='SolucionSani',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuestovivitot',
            name='Transporte',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
