# Generated by Django 3.2.5 on 2024-04-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClienteApp', '0002_initial'),
        ('ConfiguracionApp', '0002_initial'),
        ('SolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInscSeg',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('MontosAsegAnt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('NuevoMontAse', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MontoTotaAse', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Plazo', models.CharField(max_length=10)),
                ('Garantia', models.CharField(max_length=50)),
                ('Estatura', models.CharField(max_length=15)),
                ('Peso', models.CharField(max_length=15)),
                ('DesignoBene', models.CharField(max_length=30)),
                ('IdSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.solicitud')),
            ],
            options={
                'verbose_name': 'SolicitudInscSeg',
                'verbose_name_plural': 'SolicitudInscSegs',
                'db_table': 'SolicitudInscSeg',
            },
        ),
        migrations.CreateModel(
            name='SolicitudInscSegPad',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FechaPade', models.DateField(blank=True, null=True)),
                ('TratamientoReci', models.CharField(max_length=200)),
                ('SituacionActu', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=10)),
                ('IdPerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClienteApp.perfil')),
                ('IdSolicitudInscSegEnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.solicitudinscsegenf')),
            ],
            options={
                'verbose_name': 'SolicitudInscSegPad',
                'verbose_name_plural': 'SolicitudInscSegPads',
                'db_table': 'SolicitudInscSegPad',
            },
        ),
        migrations.CreateModel(
            name='SolicitudInscSegDefAmpDefFis',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TieneDefoAmpDefFis', models.CharField(max_length=5)),
                ('DetallesDefoAmpDefFis', models.CharField(max_length=50)),
                ('FumaCigaPip', models.CharField(max_length=5)),
                ('CuantosDia', models.CharField(max_length=15)),
                ('BebidasAlco', models.CharField(max_length=5)),
                ('FrecuenciaBebiAlc', models.CharField(max_length=25)),
                ('TratamientoMedi', models.CharField(max_length=5)),
                ('DetalleTratMed', models.CharField(max_length=50)),
                ('PracticaActiDep', models.CharField(max_length=5)),
                ('ClaseActiDep', models.CharField(max_length=25)),
                ('FrecuenciaActiDep', models.CharField(max_length=25)),
                ('SeguroDese', models.CharField(max_length=5)),
                ('IdSolicitudInscSeg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudInscripcionSApp.solicitudinscseg')),
            ],
            options={
                'verbose_name': 'SolicitudInscSegDefAmpDefFis',
                'verbose_name_plural': 'SolicitudInscSegDefAmpDefFiss',
                'db_table': 'SolicitudInscSegDefAmpDefFis',
            },
        ),
    ]
