# Generated by Django 3.2.5 on 2024-04-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteDatoGen',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Codigo', models.CharField(max_length=10)),
                ('CalidadActu', models.CharField(max_length=10)),
                ('NombreConzCli', models.CharField(max_length=60)),
                ('ConocidoComo', models.CharField(max_length=60)),
                ('Nacionalidad', models.CharField(max_length=50)),
                ('DocumentoIden', models.CharField(max_length=5)),
                ('NumeroDocu', models.CharField(max_length=40)),
                ('FechaVencdoc', models.DateField(blank=True, null=True)),
                ('DireccionDomi', models.CharField(max_length=100)),
                ('CorreoElec', models.CharField(max_length=50)),
                ('TelefonoCelu', models.CharField(max_length=10)),
                ('TelefonoFijo', models.CharField(max_length=10)),
                ('EstatusProp', models.CharField(max_length=60)),
                ('NombreCony', models.CharField(max_length=60)),
                ('Estado', models.CharField(max_length=10)),
                ('IdSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolicitudesApp.solicitud')),
            ],
            options={
                'verbose_name': 'ClienteDatoGen',
                'verbose_name_plural': 'ClienteDatoGens',
                'db_table': 'ClienteDatoGen',
            },
        ),
        migrations.CreateModel(
            name='ClienteReciRemFam',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('RecibeReme', models.CharField(max_length=5)),
                ('NombreRemi', models.CharField(max_length=40, null=True)),
                ('Parentesco', models.CharField(max_length=15, null=True)),
                ('PaisOrig', models.CharField(max_length=15, null=True)),
                ('Monto', models.CharField(max_length=20, null=True)),
                ('Estado', models.CharField(max_length=10)),
                ('IdClienteDatoGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConozcaClienteApp.clientedatogen')),
            ],
            options={
                'verbose_name': 'ClienteReciRemFam',
                'verbose_name_plural': 'ClienteReciRemFams',
                'db_table': 'ClienteReciRemFam',
            },
        ),
        migrations.CreateModel(
            name='ClientePersBen',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NoApli', models.CharField(max_length=10, null=True)),
                ('NombreComp', models.CharField(max_length=60, null=True)),
                ('DireccionPerm', models.CharField(max_length=50, null=True)),
                ('TipoDocuPers', models.CharField(max_length=10, null=True)),
                ('NumeroDocuPers', models.CharField(max_length=20, null=True)),
                ('BeneficiarioPeps', models.CharField(max_length=5, null=True)),
                ('Estado', models.CharField(max_length=10)),
                ('IdClienteDatoGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConozcaClienteApp.clientedatogen')),
            ],
            options={
                'verbose_name': 'ClientePersBen',
                'verbose_name_plural': 'ClientePersBens',
                'db_table': 'ClientePersBen',
            },
        ),
        migrations.CreateModel(
            name='ClientePerfTra',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Prestamos', models.CharField(max_length=50, null=True)),
                ('EspecificarOtroPer', models.CharField(max_length=50, null=True)),
                ('Estado', models.CharField(max_length=10)),
                ('IdClienteDatoGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConozcaClienteApp.clientedatogen')),
            ],
            options={
                'verbose_name': 'ClientePerfTra',
                'verbose_name_plural': 'ClientePerfTras',
                'db_table': 'ClientePerfTra',
            },
        ),
        migrations.CreateModel(
            name='ClientePeps',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UstedPeps', models.CharField(max_length=5)),
                ('RelacionPeps', models.CharField(max_length=20)),
                ('NombrePeps', models.CharField(max_length=60, null=True)),
                ('PuestoDese', models.CharField(max_length=50, null=True)),
                ('PeriodoGestDes', models.CharField(max_length=20, null=True)),
                ('PeriodoGestHas', models.CharField(max_length=20, null=True)),
                ('Grado', models.CharField(max_length=10, null=True)),
                ('Parentesco', models.CharField(max_length=30, null=True)),
                ('Estado', models.CharField(max_length=10)),
                ('IdClienteDatoGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConozcaClienteApp.clientedatogen')),
            ],
            options={
                'verbose_name': 'ClientePeps',
                'verbose_name_plural': 'ClientePepss',
                'db_table': 'ClientePepss',
            },
        ),
        migrations.CreateModel(
            name='ClienteParaUsoExc',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ValideFirmNomFot', models.CharField(max_length=5)),
                ('VerifiqueDire', models.CharField(max_length=5)),
                ('VerificadoPor', models.CharField(max_length=60)),
                ('CodigoEmpl', models.CharField(max_length=30)),
                ('Estado', models.CharField(max_length=10)),
                ('IdClienteDatoGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConozcaClienteApp.clientedatogen')),
            ],
            options={
                'verbose_name': 'ClienteParaUsoExc',
                'verbose_name_plural': 'ClienteParaUsoExcs',
                'db_table': 'ClienteParaUsoExc',
            },
        ),
        migrations.CreateModel(
            name='ClienteDeclCli',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ClasificacionCred', models.CharField(max_length=30)),
                ('MontoDeclCli', models.CharField(max_length=30)),
                ('CuotaDeclCli', models.CharField(max_length=30)),
                ('RealizarPagoAdi', models.CharField(max_length=5)),
                ('ProcedenciaPagoAdi', models.CharField(max_length=50, null=True)),
                ('Estado', models.CharField(max_length=10)),
                ('IdClienteDatoGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConozcaClienteApp.clientedatogen')),
            ],
            options={
                'verbose_name': 'ClienteDeclCli',
                'verbose_name_plural': 'ClienteDeclClis',
                'db_table': 'ClienteDeclCli',
            },
        ),
        migrations.CreateModel(
            name='ClienteDatoNeg',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreNego', models.CharField(max_length=50)),
                ('ProductoServ', models.CharField(max_length=200)),
                ('DireccionNego', models.CharField(max_length=50)),
                ('FechaInicAct', models.DateField(blank=True, null=True)),
                ('RangoIngrMen', models.CharField(max_length=20)),
                ('OtrosIngrMen', models.CharField(max_length=15)),
                ('ProcedenciaOtroIng', models.CharField(max_length=30, null=True)),
                ('Estado', models.CharField(max_length=10)),
                ('IdClienteDatoGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConozcaClienteApp.clientedatogen')),
            ],
            options={
                'verbose_name': 'ClienteDatoNeg',
                'verbose_name_plural': 'ClienteDatoNegs',
                'db_table': 'ClienteDatoNeg',
            },
        ),
        migrations.CreateModel(
            name='ClienteActiEco',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TipoActi', models.CharField(max_length=20)),
                ('LugarTrab', models.CharField(max_length=50)),
                ('CargoDese', models.CharField(max_length=50)),
                ('TiempoLabo', models.CharField(max_length=20)),
                ('ProcedenciaFond', models.CharField(max_length=30)),
                ('RangoIngrMen', models.CharField(max_length=20)),
                ('OtrosIngr', models.CharField(max_length=15)),
                ('ProcedenciaOtroIng', models.CharField(max_length=30, null=True)),
                ('Estado', models.CharField(max_length=10)),
                ('IdClienteDatoGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConozcaClienteApp.clientedatogen')),
            ],
            options={
                'verbose_name': 'ClienteActiEco',
                'verbose_name_plural': 'ClienteActiEcos',
                'db_table': 'ClienteActiEco',
            },
        ),
    ]
