# Generated by Django 3.2.5 on 2024-04-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClienteApp', '0001_initial'),
        ('DireccionApp', '0001_initial'),
        ('ConfiguracionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilnoapl',
            name='IdAgencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.agencia'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='IdAgencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.agencia'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='IdDistrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DireccionApp.distrito'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='IdOcupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConfiguracionApp.ocupacion'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='IdOcupacionDUI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocupacion_DUI', to='ConfiguracionApp.ocupacion'),
        ),
    ]
